"""
This type stub file was generated by pyright.
"""

from typing import Callable
from pygame_widgets.widget import WidgetBase

class ProgressBar(WidgetBase):
    def __init__(self, win, x, y, width, height, progress: Callable[[], float], **kwargs) -> None:
        ...
    
    def listen(self, events): # -> None:
        ...
    
    def draw(self): # -> None:
        """ Display to surface """
        ...
    


if __name__ == '__main__':
    startTime = ...
    win = ...
    progressBar = ...
    run = ...
