"""
This type stub file was generated by pyright.
"""

from pygame_widgets.widget import WidgetBase

class TextBox(WidgetBase):
    REPEAT_DELAY = ...
    REPEAT_INTERVAL = ...
    CURSOR_INTERVAL = ...
    def __init__(self, win, x, y, width, height, isSubWidget=..., **kwargs) -> None:
        """ A customisable textbox for Pygame

        :param win: Surface on which to draw
        :type win: pygame.Surface
        :param x: X-coordinate of top left
        :type x: int
        :param y: Y-coordinate of top left
        :type y: int
        :param width: Width of button
        :type width: int
        :param height: Height of button
        :type height: int
        :param kwargs: Optional parameters
        """
        ...
    
    def listen(self, events):
        """ Wait for inputs

        :param events: Use pygame.event.get()
        :type events: list of pygame.event.Event
        """
        ...
    
    def draw(self): # -> None:
        """ Display to surface """
        ...
    
    def updateCursor(self): # -> None:
        ...
    
    def updateRepeatKey(self): # -> None:
        ...
    
    def setText(self, text): # -> None:
        ...
    
    def getText(self): # -> str:
        ...
    


if __name__ == '__main__':
    def output(): # -> None:
        ...
    
    win = ...
    textbox = ...
    run = ...
