"""
This type stub file was generated by pyright.
"""

from pygame_widgets.widget import WidgetBase

class Toggle(WidgetBase):
    def __init__(self, win, x, y, width, height, **kwargs) -> None:
        ...
    
    def toggle(self): # -> None:
        ...
    
    def listen(self, events): # -> None:
        ...
    
    def draw(self): # -> None:
        ...
    
    def getValue(self): # -> bool:
        ...
    


if __name__ == '__main__':
    win = ...
    toggle = ...
    run = ...
